### ISSUE TITLE
error when i try to run the proxy .

### ISSUE THREAD

**Issue by ingnelson** [adhu2018/python-proxy#1]
Hello.

i get this error when i try to run the proxy :

![image](https://user-images.githubusercontent.com/6626845/86966951-2b25bc00-c127-11ea-8d35-c9d3d47b0cd2.png)

python3 PythonProxy.py
```
Traceback (most recent call last):
  File "PythonProxy.py", line 87, in <module>
    from tools import filter_
ImportError: No module named 'tools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PythonProxy.py", line 88, in <module>
    except (ModuleNotFoundError, ImportError):
NameError: name 'ModuleNotFoundError' is not defined

```

 python PythonProxy.py
```
Traceback (most recent call last):
  File "PythonProxy.py", line 84, in <module>
    import _thread as thread
ImportError: No module named _thread

```

Can you fix it , please

**Comment by adhu2018** [comment]
ModuleNotFoundError is an ImportError exception that was defined only in python 3.6 and later versions.

**Comment by adhu2018** [comment]
This "filter_" is used to block ads for http protocols. ([tools.py](https://github.com/adhu2018/tools/blob/master/tools.py))  
If you don't need it, you can delete the code.
